// Verifies the end card: RETRY restarts from scratch, CONTINUE opens the GitHub profile.
import puppeteer from 'puppeteer-core';
import { spawn } from 'node:child_process';
const server = spawn('npx', ['vite', 'preview', '--port', '4173', '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 1500));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal'], defaultViewport: { width: 414, height: 800, deviceScaleFactor: 2, isMobile: true, hasTouch: true } });
const page = await browser.newPage();
const logs = [];
page.on('console', (m) => { if (/AdsTracking|PlayableAdsSDK|EndSession/.test(m.text())) logs.push(m.text()); });
page.on('pageerror', (e) => logs.push('[pageerror] ' + e.message));
await page.goto('http://localhost:4173/', { waitUntil: 'load' });
await page.waitForFunction('window.__ready === true', { timeout: 60000 });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const st = () => page.evaluate(() => window.__game.state());
await wait(4000);
await page.evaluate(() => window.__game.forceLose());
await wait(3500);
console.log('endcard visible:', await page.evaluate(() => document.querySelector('.endcard').classList.contains('on')), (await st()).phase);
await page.tap('.endcard .retry');
await wait(500);
console.log('after RETRY:', await st(), 'endcard visible:', await page.evaluate(() => document.querySelector('.endcard').classList.contains('on')));
await wait(3500);
console.log('after intro:', (await st()).phase);
await page.evaluate(() => window.__game.forceLose());
await wait(3500);
const newTarget = browser.waitForTarget((t) => t.url().includes('github.com'), { timeout: 8000 }).then((t) => t.url()).catch(() => 'none');
await page.tap('.endcard .cta');
console.log('CONTINUE opened:', await newTarget);
console.log(logs.filter((l) => /CHALLENGE_STARTED|ENDCARD|stopAds|open store|pageerror/.test(l)).join('\n'));
await browser.close();
server.kill();
